FEATURE: More descriptive personal courses page
ucsb-cs156-w24/proj-courses-w24-5pm-4 pull request #28
Opened 2024-02-29 21:36 UTC by Torry051

Add Course Name, Schedule Name, and Quarter for Course Page.

<img width="1193" alt="course" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/129719123/ca216136-af5f-4c69-a913-244b2e99419b">

https://proj-courses-torry051-dev.dokku-08.cs.ucsb.edu/

Close #4

2024-03-06 01:28 UTC, tallyhawley commented
I would love to be able to access this information without having to manually enter it on the CourseForm.

2024-03-06 01:30 UTC, tallyhawley requested changes
I would love to be able to access this information without having to manually enter it on the CourseForm.
Please take a look at how they access course information in the Personal Schedule Details page. (Also, please format quarters in QYY format, not YYYYQ. There is a helper function to do this.)

2024-03-08 20:00 UTC, Torry051 commented
Solve all issues and waiting for code review.

<img width="1175" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/129719123/d3cdb711-3d33-4340-b564-32a54c923916">

My dokku App linked to another branch now. I will update dokku deployment latter.

2024-03-11 09:13 UTC, tallyhawley requested changes
some small changes, should be really quick! & please update your dokku so i can test this out :)

2024-03-11 09:13 UTC, tallyhawley commented on .DS_Store
remove this

2024-03-11 09:13 UTC, tallyhawley commented on frontend/package-lock.json
remove these changes from your PR

2024-03-11 09:13 UTC, tallyhawley commented on frontend/src/tests/components/Courses/CourseForm.test.js
> +
dead code/commented out? delete this

2024-03-11 09:13 UTC, tallyhawley commented on frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
> +        // courseName: "CMPSC",
just delete this if it's going to be commented out anyway

2024-03-11 09:13 UTC, tallyhawley commented on frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
> +    // fireEvent.change(courseNameField, { target: { value: "CMPSC" } });
same here

2024-03-11 23:09 UTC, Torry051 commented
https://proj-courses-torry051-dev.dokku-08.cs.ucsb.edu

deployment update and files removed.

2024-03-12 01:55 UTC, tallyhawley commented
Getting 404 error?
<img width="1242" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/20908336/4d4374d3-dc7d-4275-ad08-f122f2ec64ea">

2024-03-12 04:37 UTC, Torry051 commented
> Getting 404 error? <img alt="image" width="1242" src="https://private-user-images.githubusercontent.com/20908336/311914095-4d4374d3-dc7d-4275-ad08-f122f2ec64ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTY1MDgsIm5iZiI6MTcxMDIxNjIwOCwicGF0aCI6Ii8yMDkwODMzNi8zMTE5MTQwOTUtNGQ0Mzc0ZDMtZGM3ZC00Mjc1LWFkMDgtZjEyMmYyZWM2NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmU1MzVmYjg0ODVmNTg0MzNmY2MzY2I4MTE1MTRhN2FiZTI5OTI5MjQwOTkxYjA4ZDQ4NGQ4MmI1OWZiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHyG5Xu594LBgRXa4gG31fhRJfpFwJ1Tawvxfc82tzY">

I think that error is because the Personal Schedule of the course has been deleted, but the course is still there.

> Getting 404 error? <img alt="image" width="1242" src="https://private-user-images.githubusercontent.com/20908336/311914095-4d4374d3-dc7d-4275-ad08-f122f2ec64ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTgxNzksIm5iZiI6MTcxMDIxNzg3OSwicGF0aCI6Ii8yMDkwODMzNi8zMTE5MTQwOTUtNGQ0Mzc0ZDMtZGM3ZC00Mjc1LWFkMDgtZjEyMmYyZWM2NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MzExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmE4ZTYwMDA1ZWY5YTE1YmUxYThiOTJhNGQ5ZGRkNjZjN2QwYmUzYjg3MWVhMGYxODk1NGMxZWIwYjJlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_UtcnXHYzofLTMUat3wBw5ylaATZKCPD5BOnVBqA0E">

This error exists because we delete the personal schedule but not delete the course. And my backend code need to use  the psid to get all other information list in the course page.

2024-03-12 04:39 UTC, Torry051 commented
> > Getting 404 error? <img alt="image" width="1242" src="https://private-user-images.githubusercontent.com/20908336/311914095-4d4374d3-dc7d-4275-ad08-f122f2ec64ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTY1MDgsIm5iZiI6MTcxMDIxNjIwOCwicGF0aCI6Ii8yMDkwODMzNi8zMTE5MTQwOTUtNGQ0Mzc0ZDMtZGM3ZC00Mjc1LWFkMDgtZjEyMmYyZWM2NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmU1MzVmYjg0ODVmNTg0MzNmY2MzY2I4MTE1MTRhN2FiZTI5OTI5MjQwOTkxYjA4ZDQ4NGQ4MmI1OWZiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHyG5Xu594LBgRXa4gG31fhRJfpFwJ1Tawvxfc82tzY">
> 
> I think that error is because the Personal Schedule of the course has been deleted, but the course is still there.
> 
> > Getting 404 error? <img alt="image" width="1242" src="https://private-user-images.githubusercontent.com/20908336/311914095-4d4374d3-dc7d-4275-ad08-f122f2ec64ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTgxNzksIm5iZiI6MTcxMDIxNzg3OSwicGF0aCI6Ii8yMDkwODMzNi8zMTE5MTQwOTUtNGQ0Mzc0ZDMtZGM3ZC00Mjc1LWFkMDgtZjEyMmYyZWM2NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MzExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmE4ZTYwMDA1ZWY5YTE1YmUxYThiOTJhNGQ5ZGRkNjZjN2QwYmUzYjg3MWVhMGYxODk1NGMxZWIwYjJlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_UtcnXHYzofLTMUat3wBw5ylaATZKCPD5BOnVBqA0E">
> 
> This error exists because we delete the personal schedule but not delete the course. And my backend code need to use the psid to get all other information list in the course page.

So, I still need to show the course with extra description when the ps has been deleted?

2024-03-12 07:35 UTC, Torry051 commented
When the schedule are delete, the courses not delete, will still show in index page.
<img width="1215" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/129719123/daa3faf5-7d92-40f5-90a9-77ae65b68422">

<img width="1204" alt="image" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/129719123/6cbc0931-05a2-46ed-99b9-9fb0a7a9e6f9">

2024-03-12 22:36 UTC, tallyhawley approved these changes
LGTM

2024-03-12 22:49 UTC, anirudhiyer1 approved these changes
LGTM

2024-03-12 23:18 UTC, merged