REFACTOR: Simplify "Personal schedule" navigation
ucsb-cs156-w24/proj-courses-w24-5pm-4 pull request #34
Opened 2024-03-04 23:17 UTC by anirudhiyer1

Changed the drop down menu for personal schedules, which previously showed "All schedules, create schedules, all courses, and create courses" to two buttons to simplify the schedules. 
Screenshots:
<img width="890" alt="Screenshot 2024-03-04 at 3 12 36 PM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/97644421/feff5b94-e589-4ba3-9bf7-b360a3913c2c">

<img width="1440" alt="Screenshot 2024-03-04 at 3 15 12 PM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/97644421/d3da85c0-decb-4337-98e6-b08756d36825">
<img width="1440" alt="Screenshot 2024-03-04 at 3 15 29 PM" src="https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/97644421/78c859eb-cd1a-4766-98de-602facbf7486">

Closes #7

2024-03-06 01:46 UTC, tallyhawley submitted a review, later dismissed
Please don't commit the `node_modules` folder. Why is it even there?

Also, please include a dokku link so that we can test your functionality.

2024-03-06 01:53 UTC, anirudhiyer1 commented
> Please don't commit the `node_modules` folder. Why is it even there?
> 
> Also, please include a dokku link so that we can test your functionality.

I did git add . but I have done that command before with seemingly no issues, I am not sure what happened. How do I decommit the folder?

2024-03-08 01:10 UTC, Torry051 submitted a review, later dismissed
LGTM

2024-03-08 01:19 UTC, anirudhiyer1 commented
@tallyhawley I was wondering if you could review this pull request. Thanks!

2024-03-08 01:54 UTC, tallyhawley requested changes

2024-03-08 01:54 UTC, tallyhawley commented on frontend/src/tests/components/Nav/AppNavbar.test.js
Don't comment-out dead tests. Please remove them if they're no longer relevant.

2024-03-08 01:54 UTC, tallyhawley commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Incomplete test?

2024-03-08 02:30 UTC, anirudhiyer1 commented on frontend/src/tests/components/Nav/AppNavbar.test.js
Removed irrelevant tests

2024-03-08 02:31 UTC, anirudhiyer1 commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Added test contents

2024-03-08 02:32 UTC, anirudhiyer1 commented
I made the changes could you check them again? @tallyhawley

2024-03-08 03:29 UTC, tallyhawley commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
What is this testing exactly?

2024-03-08 03:32 UTC, anirudhiyer1 commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
I think it is supposed to test whether the create page renders after clicking on the button. I am not sure though because I was not the one that implemented the blank function.

2024-03-08 03:57 UTC, samanthwest submitted a review, later dismissed
LGTM

2024-03-08 18:44 UTC, tallyhawley commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
There are already tests checking if the create page renders. Do you have anything checking if, for example, clicking on the "create" button navigates to the correct page?

2024-03-09 19:39 UTC, anirudhiyer1 commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Oh I see. I have deleted that test and added one that checks if it navigates correctly thanks for the feedback

2024-03-11 09:08 UTC, tallyhawley approved these changes
Looks good to me :)

2024-03-11 17:58 UTC, megumi-ondo approved these changes
LGTM

2024-03-11 20:31 UTC, merged